### ISSUE TITLE
how to execute the example python script ?

### ISSUE THREAD

**Issue by vonavage** [EasyPost/syslog-rfc5424-parser#5]
tried 
`python    example_syslog_server.py   --bind-path 514`
do not see any error ; also did not see any output

**Comment by Roguelazer** [comment]
That would start it up binding to a UNIX domain socket with the path of `./514`; that may or may not be what you want. The example script doesn't listen on TCP ports, but you should be able to modify it for your own use-case pretty straightforwardly.

It only prints something out of a message is received.

**Comment by vonavage** [comment]
thanks @Roguelazer 
Sorry could not follow the steps required to build and test the parser.
should I do `python setup.py` that did not work as well . could not find in ReadMe. Please point me to the docs

**Comment by vonavage** [comment]
In fact I changed to some other port (above 10000) and tried with valid syslog message passed on to the port, that did not work as well.

**Comment by vonavage** [comment]
@Roguelazer  does these steps seem right?
#1 
` python    example_syslog_server.py   --bind-path  10003`
#2 
`echo "<31>1 2017-11-24T05:14:15.000008-07:00 192.0.0.1 mypid 8888 - - Test syslogparser" | nc localhost  10003`

**Comment by Roguelazer** [comment]
As I said, the `--bind-path` argument is _not_ a port, it's a filesystem path at which a stream-mode unix domain socket will be created.

Here's a session of me setting it up and using it:

```
$ python -m virtualenv env
New python executable in /Users/jbrown/pg/syslog-rfc5424-parser/env/bin/python2.7
Also creating executable in /Users/jbrown/pg/syslog-rfc5424-parser/env/bin/python
Installing setuptools, pip, wheel...
done.
$ env/bin/pip install .
Looking in indexes: https://pypi.org/simple, https://pyshop.easypo.net/simple/
Processing /Users/jbrown/pg/syslog-rfc5424-parser
Collecting pyparsing>=2.0 (from syslog-rfc5424-parser==0.1.3)
  Using cached https://files.pythonhosted.org/packages/71/e8/6777f6624681c8b9701a8a0a5654f3eb56919a01a78e12bf3c73f5a3c714/pyparsing-2.3.0-py2.py3-none-any.whl
Collecting enum34 (from syslog-rfc5424-parser==0.1.3)
  Using cached https://files.pythonhosted.org/packages/c5/db/e56e6b4bbac7c4a06de1c50de6fe1ef3810018ae11732a50f15f62c7d050/enum34-1.1.6-py2-none-any.whl
Building wheels for collected packages: syslog-rfc5424-parser
  Running setup.py bdist_wheel for syslog-rfc5424-parser ... done
  Stored in directory: /Users/jbrown/Library/Caches/pip/wheels/21/e8/63/0fba71019ab56ceb789ded5206b28f2eef0522f47048f8da88
Successfully built syslog-rfc5424-parser
Installing collected packages: pyparsing, enum34, syslog-rfc5424-parser
Successfully installed enum34-1.1.6 pyparsing-2.3.0 syslog-rfc5424-parser-0.1.3
$ env/bin/python example_syslog_server.py  --bind-path example_path
```

from another shell (in the same directory), I ran
```
$ echo "<31>1 2017-11-24T05:14:15.000008-07:00 192.0.0.1 mypid 8888 - - Test syslogparser" | socat - ./example_path
```

That resulted in the first shell printing out the following:
```
{"procid": 8888, "severity": "debug", "appname": "mypid", "timestamp": "2017-11-24T05:14:15.000008-07:00", "hostname": "192.0.0.1", "facility": "daemon", "version": 1, "msgid": null, "msg": "Test syslogparser\n", "sd": {}}
```

**Comment by vonavage** [comment]
Thanks @Roguelazer ! worked fine, finally ... i have a syslog file that I need to parse ..any suggestion where to start

**previous errors**
`sudo env/bin/python example_syslog_server.py  --bind-path /home/myself/a.txt`
# without sudo fails with permission issue
# without filename at the end fails with "directory" error 

`echo "<31>1 2017-11-24T05:14:15.000008-07:00 192.0.0.1 mypid 8888 - - Test syslogparser" | socat -  /home/myself/a.txt`
# error received as 
2018/11/28 15:28:37 socat[13202] E connect(5, AF=1 "/home/myself/a.txt", 23): Permission denied

**Comment by vonavage** [comment]
instead of the test python script, will use read file and use  `SyslogMessage.parse(messageLine)`

**Comment by vonavage** [comment]
thankyou @Roguelazer  worked fine reading from file
