### ISSUE TITLE
Fails to correct parse messages with empty SD using pyparsing 2.3.1

### ISSUE THREAD

**Issue by tfogwill** [EasyPost/syslog-rfc5424-parser#6]
According to RFC5424, if SD is empty is should be NILVALUE ('-').

In syslog_rfc5424_parser/message.py, when using pyparsing 2.3.1, structured_data is parsed as a list (i.e. ['-'], so the check on line 108 fails.

To reproduce:
pip uninstall pyparsing
pip install pyparsing==2.3.1 --force-reinstall
echo 'from syslog_rfc5424_parser import SyslogMessage; mesg = "<85>1 2019-01-15T09:19:30.715Z hostname appname 28121 some-msg-id - This is the message"; print(SyslogMessage.parse(mesg))' | python

**Comment by Roguelazer** [comment]
Confirmed, investigating now.

**Comment by Roguelazer** [comment]
Yeah this is the grouping behavior change in 2.3. I will work on making this service 2.3 compatible and in the meantime have pushed a quickfix to master (as version 0.1.5) pinning it to older versions.
